#!/bin/bash
# Инструкция по очистке кэша браузера для исправления редирект-петли

echo "=========================================="
echo "Исправление редирект-петли в браузере"
echo "=========================================="
echo ""
echo "Проблема: Браузер показывает 'слишком много редиректов'"
echo "Причина: HSTS заголовок сохранен в кэше браузера"
echo ""
echo "РЕШЕНИЕ:"
echo ""
echo "1. CHROME/EDGE:"
echo "   - Откройте: chrome://net-internals/#hsts"
echo "   - В разделе 'Delete domain security policies'"
echo "   - Введите: 3931b3fe50ab.vps.myjino.ru"
echo "   - Нажмите 'Delete'"
echo ""
echo "2. FIREFOX:"
echo "   - Откройте: about:config"
echo "   - Найдите: security.tls.insecure_fallback_hosts"
echo "   - Добавьте домен или очистите через настройки"
echo ""
echo "3. ОБЩЕЕ:"
echo "   - Очистите кэш и cookies для домена"
echo "   - Или используйте режим инкогнито"
echo "   - Или попробуйте другой браузер"
echo ""
echo "4. ВРЕМЕННОЕ РЕШЕНИЕ:"
echo "   - Используйте HTTP: http://3931b3fe50ab.vps.myjino.ru/"
echo ""
echo "=========================================="

